/* eslint-disable jsx-a11y/anchor-is-valid */
/* eslint-disable jsx-a11y/alt-text */
import { React, useEffect } from "react";
import { useState } from "react";
import AuthService from "../services/auth.service";
import { Link } from "react-router-dom";
function Navbar() {
  const [showModeratorBoard, setShowModeratorBoard] = useState(false);
  const [showAdminBoard, setShowAdminBoard] = useState(false);
  const [currentUser, setCurrentUser] = useState(undefined);

  useEffect(() => {
    const user = AuthService.getCurrentUser();

    if (user) {
      setCurrentUser(user);
      setShowModeratorBoard(user.roles.includes("ROLE_MODERATOR"));
      setShowAdminBoard(user.roles.includes("ROLE_ADMIN"));
    }

    // Adding the event listener for ChatGPT button
    const chatGptButton = document.getElementById("chatgptButton");
    if (chatGptButton) {
      chatGptButton.addEventListener("click", function (event) {
        event.preventDefault(); // Prevent immediate navigation to the link

        // The prompt text to copy
        const textToCopy = `Hello, I need help with my health concerns.
        Below, I will provide details regarding my symptoms and health issues, 
        my name:- 
        Symptoms I notice:- 
        Other relevant details:- 
        I would like you to provide a basic remedial solution that I can use at home, along with suggestions for any medications, tablets, creams, syrups, or other treatments appropriate for my condition. Additionally, please provide a brief explanation of my problem, including why it might be occurring.
        Finally, format the output to resemble a doctor's lab report, as if it were generated by a healthcare professional, so that it feels official and informative.
        Lab Report: Doctor Nexus Remedies and Treatment Recommendations
        Date: [Insert Today's Date by ChatGPT]
        Physician Signature:
        by Kunal Verma & Kunal Bobde
        Contact Information: XXXXX-94684
        Thank you!`;


        // Copy text to clipboard
        navigator.clipboard
          .writeText(textToCopy)
          .then(() => {
            alert("Text copied to clipboard!\n\n▪ Paste it out as GPT's prompt. \n▪ Fill the details as per you. \n▪ Change the prompt while pasting according to you.");

            // After copying, navigate to ChatGPT
            window.open("https://myninja.ai", "_self");
          })
          .catch((err) => {
            console.error("Failed to copy text: ", err);
          });
      });
    }

    // Clean up the event listener when component unmounts
    return () => {
      if (chatGptButton) {
        chatGptButton.removeEventListener("click", () => {});
      }
    };
  }, []);

  const logOut = () => {
    AuthService.logout();
  };
  return (
    <div>
     
        {currentUser ? (
           <div className="header">
           <div className="header-left">
             <a className="logo">
               <img src="assets/img/logo.png" width={35} height={35} alt="logo" />{" "}
               <span>Doctor Nexus</span>
             </a>
           </div>
          <div className="main-wrapper">
            <div>
              <div>
                <a id="toggle_btn" href="javascript:void(0);">
                  <i className="fa fa-bars" />
                </a>
                <a
                  id="mobile_btn"
                  className="mobile_btn float-left"
                  href="#sidebar"
                >
                  <i className="fa fa-bars" />
                </a>

                <ul className="nav user-menu float-right">
                <li className="nav-item active"><Link className="nav-link" underline="none" variant="subtitle2" component={Link} to="/">
                          <span >Home</span>
                       </Link>
                       </li>
                       { currentUser.role ==='patient' ? (
                       <li className="nav-item active"><Link className="nav-link" underline="none" variant="subtitle2" component={Link} to="/patient/app">
                          <span >My Space</span>
                       </Link></li>
                       ):(
                       
                       <div></div>
                       )}

                       { currentUser.role ==='doctor' ? (
                       <li className="nav-item active"><Link className="nav-link" underline="none" variant="subtitle2" component={Link} to="/doctor/app">
                          <span >My Space</span>
                       </Link></li>
                       ):(
                       
                       <div></div>
                       )}

                <li className="nav-item">        
                 <Link className="nav-link" underline="none" variant="subtitle2" component={Link} to="/shop">
                    <span>Shop</span>
                 </Link>     
        </li>    
        <li className="nav-item">        
                       <Link className="nav-link" underline="none" variant="subtitle2" component={Link} to="/blog">
                          <span>Blog</span>
                       </Link>     
              </li> 
              <li className="nav-item">        
                       <Link className="nav-link" underline="none" variant="subtitle2" component={Link} to="/team">
                          <span>About</span>
                       </Link>     
              </li>
              <li className="nav-item">        
                       <Link className="nav-link" underline="none" variant="subtitle2" component={Link} to="/contact">
                          <span>Contact Us</span>
                       </Link>     
              </li>    
        
                  <li className="nav-item dropdown has-arrow">
                    <a
                      href="#"
                      className="dropdown-toggle nav-link user-link"
                      data-toggle="dropdown"
                    >
                      <span className="user-img">
                        <img
                          className="rounded-circle"
                          src="assets/img/user.jpg"
                          width={24}
                          alt="Admin"
                        />
                        <span className="status online" />
                      </span>
                      <span>{currentUser.username}</span>
                    </a>
                    <div className="dropdown-menu">
                      { currentUser.role ==='patient' ? (
                           <Link
                           className="dropdown-item"
                           to={`/patient/edit-doctor/${currentUser.id}`}
                           component={Link}
                         >
                           Edit Profile
                         </Link>
                       ):(
                       
                       <div></div>
                       )}

                       { currentUser.role ==='doctor' ? (
                           <Link
                           className="dropdown-item"
                           to={`/doctor/edit-doctor/${currentUser.id}`}
                           component={Link}
                         >
                           Edit Profile
                         </Link>
                       ):(
                       
                       <div></div>
                       )}            
                      <a
                        className="dropdown-item"
                        href="/login"
                        onClick={logOut}
                      >
                        Logout
                      </a>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
          </div>
          </div>
        ) : (
          <nav className="navbar navbar-expand-lg navbar-dark ftco_navbar  ftco-navbar-light" id="ftco-navbar">
          <div className="container">
          <img src="assets/img/logo.png" width={35} height={35} alt="logo" />{" "}
           &nbsp;
            <a className="navbar-brand" href="">Doctor <span >Nexus</span></a>
            <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
              <span className="oi oi-menu" /> Menu
            </button>
            <div className="collapse navbar-collapse" id="ftco-nav">
              <ul className="navbar-nav ml-auto">
                <li className="nav-item active"><Link className="nav-link" underline="none" variant="subtitle2" component={Link} to="/">
                          <span >Home</span>
                       </Link></li>
                       <li className="nav-item">        
                       <Link className="nav-link" underline="none" variant="subtitle2" component={Link} to="/team">
                          <span>About</span>
                       </Link>     
              </li>
              


                       {/* <li className="nav-item">        
                       <Link className="nav-link" underline="none" variant="subtitle2" component={Link} to="/price">
                          <span>Pricing</span>
                       </Link>     
              </li> 
                        <li className="nav-item">        
                       <Link className="nav-link" underline="none" variant="subtitle2" component={Link} to="/blog">
                          <span>Blog</span>
                       </Link>     
              </li>
              <li className="nav-item">        
                 <Link className="nav-link" underline="none" variant="subtitle2" component={Link} to="/shop">
                    <span>Shop</span>
                 </Link>     
              </li>
              <li className="nav-item cta">        
                       <Link className="nav-link" underline="none" variant="subtitle2" component={Link} to="/role">
                          <span>Get Started</span>
                       </Link>     
              </li>
                       */}
                     


                       <li className="nav-item">        
                       <Link className="nav-link" underline="none" variant="subtitle2" component={Link} to="/contact">
                          <span>Contact Us</span>
                       </Link>     
              </li> 

              <li className="nav-item cta">        
                      <a 
                          className="navbar-brand" 
                          href="https://chatgpt.com/?temporary-chat=true" 
                          target="_self" 
                          rel="noopener noreferrer"
                          id="chatgptButton"
                          >
                          <span>Doctor - AI</span>
                      </a>    
              </li>    


               
              </ul>
            </div>
          </div>
        </nav>
        )}

      </div>
  );
}

export default Navbar;
